### ISSUE TITLE
More info how to obtain api key

### ISSUE THREAD

**Issue by blowk** [JaccoR/hass-entso-e#1]
Maybe add the following to readme file for future users how to obtain api key.

To request access to the Restful API, please register on the Transparency Platform and send an email to transparency@entsoe.eu with “Restful API access” in the subject line. Indicate the email address you entered during registration in the email body. The ENTSO-E Helpdesk will make their best efforts to respond to your request within 3 working days.

**Comment by JaccoR** [comment]
Thanks, I added it!
