### ISSUE TITLE
How to display next day prices ?

### ISSUE THREAD

**Issue by Vinisz** [JaccoR/hass-entso-e#102]
Hi,

Like the component, works great, I do have one question.
My energy provider updates prices for next day at around 15:00.
Is there a way to display prices for the next day once they are available ? 
Use case: Like to schedule over-night car charging or washing machine if prices for upcoming night are cheap.

**Comment by fluppie** [comment]
+1 :-)

**Comment by AOskam** [comment]
You can change te span of the apex chart to 48 hours if that's what you're looking for? Then you get a graph showing next day prices as well when available.

**Comment by Vinisz** [comment]
Sorry, forgot to come back on this topic.
I have indeed that and it works great, the graph auto-updates when new prices become available just perfect.
Just for sharing, I also added some colors based on thresholds, giving a perfect overview on whet energy is cheap, thanks `!

Sharing my card code for inspiration:

`type: custom:apexcharts-card
graph_span: 28h
experimental:
  color_threshold: true
span:
  start: hour
header:
  show: true
  title: Stroomprijs (€/kWh)
series:
  - entity: sensor.average_electricity_price_today
    stroke_width: 2
    float_precision: 2
    type: column
    opacity: 1
    color: ''
    data_generator: |
      return entity.attributes.prices.map((record, index) => {
        return [record.time, record.price];
      });
    color_threshold:
      - value: 0
        color: brown
        opacity: 1
      - value: 0.01
        color: green
      - value: 0.15
        color: orange
      - value: 0.25
        color: red
yaxis:
  - id: Prijs
    decimals: 2
    min: 0
`
