### ISSUE TITLE
something is wrong with today's prices. tomorrow and today are switched 

### ISSUE THREAD

**Issue by whulshof** [JaccoR/hass-entso-e#104]
the average_price attributes are wrong since today. price_today and prices_tomorrow are swapped for some reason. Anybody know why?

**Comment by whulshof** [comment]
Hmmmm.... suddenly it seems to be alright again. But 5 minutes ago they were swapped.

**Comment by RafaelDuncan** [comment]
yes, I recognize that.. at the moment I suffer from that too.

**Comment by MrOzzOnline** [comment]
This seems to be related to #98

**Comment by noelie88** [comment]
I think I have something similar. When I look at the list of todays (28-1-24 13:50) prices. I still also see yesterdays prices. The maximum price today (HA entity: sensor.tibber_highest_energy_price_today) is showing 0.26955 as the highest price. Though this was yesterdays highest price. Todays actual highest price is 0.246 euro. Not sure where to start looking.

state_class: measurement
prices_today: 
- time: '2024-01-28 00:00:00+01:00'
  price: 0.23422
- time: '2024-01-28 01:00:00+01:00'
  price: 0.22687
- time: '2024-01-28 02:00:00+01:00'
  price: 0.22494
- time: '2024-01-28 03:00:00+01:00'
  price: 0.22468
- time: '2024-01-28 04:00:00+01:00'
  price: 0.22599
- time: '2024-01-28 05:00:00+01:00'
  price: 0.22894
- time: '2024-01-28 06:00:00+01:00'
  price: 0.22521
- time: '2024-01-28 07:00:00+01:00'
  price: 0.22479
- time: '2024-01-28 08:00:00+01:00'
  price: 0.22506
- time: '2024-01-28 09:00:00+01:00'
  price: 0.22024
- time: '2024-01-28 10:00:00+01:00'
  price: 0.21556
- time: '2024-01-28 11:00:00+01:00'
  price: 0.2085
- time: '2024-01-28 12:00:00+01:00'
  price: 0.20333
- time: '2024-01-28 13:00:00+01:00'
  price: 0.20213
- time: '2024-01-28 14:00:00+01:00'
  price: 0.21358
- time: '2024-01-28 15:00:00+01:00'
  price: 0.21986
- time: '2024-01-28 16:00:00+01:00'
  price: 0.23364
- time: '2024-01-28 17:00:00+01:00'
  price: 0.2459
- time: '2024-01-28 18:00:00+01:00'
  price: 0.24382
- time: '2024-01-28 19:00:00+01:00'
  price: 0.23832
- time: '2024-01-28 20:00:00+01:00'
  price: 0.23645
- time: '2024-01-28 21:00:00+01:00'
  price: 0.22309
- time: '2024-01-28 22:00:00+01:00'
  price: 0.22562
- time: '2024-01-28 23:00:00+01:00'
  price: 0.22119

prices_tomorrow: 
prices: 
- time: '2024-01-27 00:00:00+01:00'
  price: 0.24357
- time: '2024-01-27 01:00:00+01:00'
  price: 0.2368
- time: '2024-01-27 02:00:00+01:00'
  price: 0.23317
- time: '2024-01-27 03:00:00+01:00'
  price: 0.22482
- time: '2024-01-27 04:00:00+01:00'
  price: 0.22178
- time: '2024-01-27 05:00:00+01:00'
  price: 0.22431
- time: '2024-01-27 06:00:00+01:00'
  price: 0.226
- time: '2024-01-27 07:00:00+01:00'
  price: 0.23438
- time: '2024-01-27 08:00:00+01:00'
  price: 0.25841
- time: '2024-01-27 09:00:00+01:00'
  price: 0.25773
- time: '2024-01-27 10:00:00+01:00'
  price: 0.25043
- time: '2024-01-27 11:00:00+01:00'
  price: 0.22643
- time: '2024-01-27 12:00:00+01:00'
  price: 0.22099
- time: '2024-01-27 13:00:00+01:00'
  price: 0.21862
- time: '2024-01-27 14:00:00+01:00'
  price: 0.2257
- time: '2024-01-27 15:00:00+01:00'
  price: 0.24805
- time: '2024-01-27 16:00:00+01:00'
  price: 0.25313
- time: '2024-01-27 17:00:00+01:00'
  price: 0.2638
- time: '2024-01-27 18:00:00+01:00'
  price: 0.26955
- time: '2024-01-27 19:00:00+01:00'
  price: 0.2655
- time: '2024-01-27 20:00:00+01:00'
  price: 0.25559
- time: '2024-01-27 21:00:00+01:00'
  price: 0.24534
- time: '2024-01-27 22:00:00+01:00'
  price: 0.24535
- time: '2024-01-27 23:00:00+01:00'
  price: 0.24139
- time: '2024-01-28 00:00:00+01:00'
  price: 0.23422
- time: '2024-01-28 01:00:00+01:00'
  price: 0.22687
- time: '2024-01-28 02:00:00+01:00'
  price: 0.22494
- time: '2024-01-28 03:00:00+01:00'
  price: 0.22468
- time: '2024-01-28 04:00:00+01:00'
  price: 0.22599
- time: '2024-01-28 05:00:00+01:00'
  price: 0.22894
- time: '2024-01-28 06:00:00+01:00'
  price: 0.22521
- time: '2024-01-28 07:00:00+01:00'
  price: 0.22479
- time: '2024-01-28 08:00:00+01:00'
  price: 0.22506
- time: '2024-01-28 09:00:00+01:00'
  price: 0.22024
- time: '2024-01-28 10:00:00+01:00'
  price: 0.21556
- time: '2024-01-28 11:00:00+01:00'
  price: 0.2085
- time: '2024-01-28 12:00:00+01:00'
  price: 0.20333
- time: '2024-01-28 13:00:00+01:00'
  price: 0.20213
- time: '2024-01-28 14:00:00+01:00'
  price: 0.21358
- time: '2024-01-28 15:00:00+01:00'
  price: 0.21986
- time: '2024-01-28 16:00:00+01:00'
  price: 0.23364
- time: '2024-01-28 17:00:00+01:00'
  price: 0.2459
- time: '2024-01-28 18:00:00+01:00'
  price: 0.24382
- time: '2024-01-28 19:00:00+01:00'
  price: 0.23832
- time: '2024-01-28 20:00:00+01:00'
  price: 0.23645
- time: '2024-01-28 21:00:00+01:00'
  price: 0.22309
- time: '2024-01-28 22:00:00+01:00'
  price: 0.22562
- time: '2024-01-28 23:00:00+01:00'
  price: 0.22119

**Comment by Roeland54** [comment]
v0.4.0 is released this version contains fixes that solve a lot of warnings and known issues. This issue is probably also solved.
Please update to the latest version.
Closing this issue for now. If you still have issue please feel free to open a new issue.
