### ISSUE TITLE
Use time of lowest price as time trigger in automation

### ISSUE THREAD

**Issue by jasperweiss** [JaccoR/hass-entso-e#107]
I wanted to create an automation that starts at the time of the lowest price but the time_of_lowest_price_today does not seem to be a proper time entity since it cannot be selected as a time trigger entity.

![image](https://user-images.githubusercontent.com/29832921/212113573-de20a121-b108-47e9-88d8-332eac03a2c0.png)

**Comment by Roeland54** [comment]
v0.4.0 is released this version contains fixes that solve a lot of warnings and known issues. This issue is probably also solved.
Please update to the latest version.
Closing this issue for now. If you still have issue please feel free to open a new issue.
