### ISSUE TITLE
Prices in c/kWh

### ISSUE THREAD

**Issue by jeveli** [JaccoR/hass-entso-e#111]
At least in Finland we use cents/kwh, and if I'm not mistaking in Sweden also "öre" 
And probably in all the countries that use €.
The Nordpool integration also have this option, so I think it will be a much appreciated option.

**Comment by sebbsee** [comment]
Yes, this would be a better option in my opinion. Also not sure why the time as in am and pm since its European energy prices.

**Comment by Roeland54** [comment]
The latest version allows to set a custom currency like "c", "cent", "öre". Then you can adjust the value template accordingly to get the correct number like this: 
![image](https://github.com/user-attachments/assets/2bc506ed-ab4d-4ee8-b911-6488a252e147)
![image](https://github.com/user-attachments/assets/e7a5e048-6565-4a9f-9b96-be319f2266b8)
