### ISSUE TITLE
Not visible in integration of HAS

### ISSUE THREAD

**Issue by Flinkaflenka** [JaccoR/hass-entso-e#112]
I installed your integration through HACS, however after restarting I do not see it appearing in the integration section or device as per your installation instructions 

"The sensors can be added using the web UI. In the web UI you can add your API-key and country and the sensors will automatically be added to your system. There is an optional field for an cost modifyer template"

Not sure what you mean with above and in which section of the UI, could you add some screenshots of what you are doing?

**Comment by JaccoR** [comment]
after adding it in hacs, you have to add it like you would any other integration. So you have to go to integrations and click add integration. Then search for Entso-e and add it.
