### ISSUE TITLE
Prices to high since a week or so

### ISSUE THREAD

**Issue by BackbierDotCom** [JaccoR/hass-entso-e#113]
Comparing to the prices from my energy company the prices from the integration are way out of band. E.g. energy next price 0,15€ integration 3,63€ how kan i fix this

**Comment by Roeland54** [comment]
v0.4.0 is released this version contains fixes that solve a lot of warnings and known issues. This issue is probably also solved.
Please update to the latest version.
Closing this issue for now. If you still have issue please feel free to open a new issue.
