### ISSUE TITLE
ENTSO-e API url changed

### ISSUE THREAD

**Issue by Teme-V** [JaccoR/hass-entso-e#115]
Entso-e api url has changed on 14th of February. New url https://web-api.tp.entsoe.eu/api

Currently no tomorrow prices available through integration

Please see announcement https://m-transparency.entsoe.eu/news/widget?id=63eb9d10f9b76c35f7d06f2e

**Comment by Tommi-V** [comment]
Looks like it's a bigger problem. Most of the services showing prices for tomorrow are not showing anything.

**Comment by Tommi-V** [comment]
Now, most of the other platforms seem to have gotten updates but ha not...

**Comment by stigvi** [comment]
Line 29 here, https://github.com/EnergieID/entsoe-py/blob/master/entsoe/entsoe.py

It is already using this url

**Comment by Teme-V** [comment]
It probably was some other issue as it started to work later in a evening
