### ISSUE TITLE
Sensor "Average Day-Ahead Electricity Price Today" doesn't update attributes. 

### ISSUE THREAD

**Issue by rupertroy** [JaccoR/hass-entso-e#117]
Since last week the sensor "Average Day-Ahead Electricity Price Today" doesn't update the attributes.  (This integration carries attributes with all prices)
The other sensors are working fine.
Any idea?

**Comment by BZBHL** [comment]
Same issue here. Manual reloading the integration does update the attributes. However, somewhere it will stop refreshing... I noticed that when stopping my firewall the refresh of the attributes is going much quicker. Is there a relation? I know that I did block some countries recently, but I don't know from which country the data is coming from. Anyone?

**Comment by BZBHL** [comment]
After changing the firewall settings, the sensor keeps up to date. Now less countries are blocked, but still no idea which country is responsible for the issue. Maybe the number of blocked countries is also playing a role? I mean, in that case the sensor took a long time to refresh... Anyone has more info about this?

**Comment by MrMark79** [comment]
I encounter the same problem. The sensor doesn't update the attributes. In my case it keeps the march 10th & 11th values. The other sensors are working fine. Even manual reloading does not change the attributes. The other ENTSO-e sensors are working fine.
Could someone look into it?
attached is a printscreen of the window with attributes, taken on march 15th.

![printscreen_2023-03-15 07-32-25](https://user-images.githubusercontent.com/8183929/225225707-0fd88204-691d-40b2-b1d4-18d3f44e449e.png)

**Comment by MrMark79** [comment]
Ok, I found the problem with my setup. I used this sensor as source for the price calculation in my energy dash. This gave errors. I removed the sensor as a price source and it worked. I hope someone can use this info to troubleshoot his own setup.

**Comment by XLR-24** [comment]
Anyone a solution for this or working on it? Have the same problem, last updated prices are from 16 March.

**Comment by MrMark79** [comment]
Hi, everyone here. I found out something. You probably have the "rotation" setting selected in your settings for ENTSO-e.
I changed it to the default "publish" now my attributes are updated, but they are updated between 12:00 and 16:00 so there is a time you don't have prices for the next day.
Cheers!

**Comment by PeterKawa** [comment]
Same here.... @MrMark79 I only have this setting 
![Screenshot from 2023-03-27 23-09-04](https://user-images.githubusercontent.com/74005072/228067244-af2a2005-fe5f-4f5f-87a0-cc2d84eb5ac2.png)
Where do I find rotation / publish settings? 
Thanks in advance

**Comment by lindsand** [comment]
I had the same problem with attributes frozen at 2023-04-14.. 

I changed the Calculation method (in integration Configuration) from sliding to publish, after that the attributes are updated again.

![image](https://user-images.githubusercontent.com/66431079/236469502-4728ae9c-ee98-4fcf-bda7-bd3f278ee2f6.png)

**Comment by Roeland54** [comment]
v0.4.0 is released this version contains fixes that solve a lot of warnings and known issues. This issue is probably also solved.
Please update to the latest version.
Closing this issue for now. If you still have issue please feel free to open a new issue.
