### ISSUE TITLE
ENTSO-e not showing as integration

### ISSUE THREAD

**Issue by stevengoossensB** [JaccoR/hass-entso-e#12]
I've added the repository via HACS, downloaded the component to custom_components, restarted HomeAssistant, but can't find the integration when trying to add it. 

Is it possible to configure this integration via the UI?

**Comment by blowk** [comment]
Yes, this integration is in HA.
After installing it through HACS and restart HA, you should normally find it when adding an integration 'ENTSO-e Transparency Platform.'

Could you find it in HACS?

**Comment by stevengoossensB** [comment]
Apparently browser cache indeed was the issue. So sorry for that!
