### ISSUE TITLE
Removing does not seem to work

### ISSUE THREAD

**Issue by PeterKawa** [JaccoR/hass-entso-e#121]
I want to config the integration, but I get this error
`Config flow could not be loaded: {"message":"Invalid handler specified"}`
Same error as when I want to re-add the integration.

I want to start all over, but somehow it cannot be uninstalled. 
Any hint how uninstall so I can start from scratch again?

**Comment by Roeland54** [comment]
v0.4.0 is released this version contains fixes that solve a lot of warnings and known issues. This issue is probably also solved.
Please update to the latest version.
Closing this issue for now. If you still have issue please feel free to open a new issue.
