### ISSUE TITLE
The prices never reflect the API (when manually calling)

### ISSUE THREAD

**Issue by maillme** [JaccoR/hass-entso-e#123]
Hello,
I can never work out why - but my prices never reflect what the actual api itself tells me (ENTSOE NL prices).... take for example just now:

- 10th April 2023
- 00:33

If I call this on the API, I get the following data for this hour: 

` <Point>
                <position>1</position>
                <price.amount>98.21</price.amount>
            </Point>`

So - if I divide this by 1000 - I get to 9.821c kwh. This reflects what my energy company tells me (Frank Energie - which does match the ENTSOE pricing when I call the API manually). 

But, in HA - the current market price (sensor.nl_energy_prices_current_electricity_market_price) tells me 0.217c kw/h. 

I have no VAT and no custom price template added. 
I'm sure this is probably something simple I am missing - but I can't seem to work out where I am going wrong with this. 

<img width="466" alt="image" src="https://user-images.githubusercontent.com/127260863/230799764-d0150f67-7b13-4ce1-bc5e-d9231de85097.png">

**Comment by toresetre** [comment]
I have the same issue here. The current_price is never the same as what Nordpool publishes. Nordpool and my provider's price aliigns with each other, but the ENTSO-e entity is always off.

**Comment by Roeland54** [comment]
v0.4.0 is released this version contains fixes that solve a lot of warnings and known issues. This issue is probably also solved.
Please update to the latest version.
Closing this issue for now. If you still have issue please feel free to open a new issue.
