### ISSUE TITLE
Sensor Average electricity price today not working anymore

### ISSUE THREAD

**Issue by chheiss** [JaccoR/hass-entso-e#126]
Hi!
Since April 8th, the integration-provided sensor Average electricity price today has stopped working.

Reinstalling did nothing to change that.

Any ideas why? It is stuck at data from April 08th.

**Comment by dieterxy** [comment]
Hi.
Same issue since April 22th.
The Average electricity price today is still updated, but the attributes "Prices today" and "Prices tomorrow" stuck and stay on the April 22th figures.
Any ideas?

**Comment by lindsand** [comment]
Hi
Same for me but stuck at 2023-04-14. after that no updates to the attributes, only "Average electricity price today (ENTSO-e)" is updated.

**Comment by lindsand** [comment]
I changed the Calculation method (in integration Configuration) from **sliding** to **publish**, after that the attributes are updated again.

![image](https://user-images.githubusercontent.com/66431079/236468506-1e81ee81-3eb1-4f1f-8b84-117921732b9f.png)

**Comment by dieterxy** [comment]
Thanks for the hint. Also worked for me.
I changed to **publish**, and after some time it got updated again.

**Comment by ThorAlex87** [comment]
Same issue here since 16th may, when home assistant lost internet for a couple of days (new router would not cooperate). Tried the change above but so far no luck, I have two instances running so I'm testing on one. When I did the change the main sensor stops working with "entity is non-numeric" error. Hoping it just takes a while...

**Comment by roymar** [comment]
Same problem here since 19-6. After home assistant had a chrash, i have a backup restored, but still the problem remains

**Comment by Arjanmus** [comment]
Same here since June 3rd. Reïnstalling, or changing to 'publish' does not help.

**Comment by morini1** [comment]
This morning suddenly there is data for today 😃

**Comment by Arjanmus** [comment]
Magically works again here too, no clue what has changed :)

**Comment by roymar** [comment]
Happy to say its working again

**Comment by RogMoe** [comment]
Remove old entso-e entry and creat new one with slightly different name solves the issue. Don't forget to adjust the new entity names in your apexchart.

**Comment by Jordenjj** [comment]
This still seems to be an issue

**Comment by DannyOosterveer** [comment]
This is a quite persistent and annoying error. I've been using the integration for over two years. Everytime the ENTSO-e API had some error, and there is no data available for some time, the integration seems to corrupt the data in sensors. Even after the data in the API is correct again, you can't use the previous sensors anymore. You'll have to delete the integration, add it again and change all our automations etc. Probably some better error handling is necessary when receiving empty or wrong data from the API...

**Comment by Roeland54** [comment]
v0.4.0 is released this version contains fixes that solve a lot of warnings and known issues. This issue is probably also solved.
Please update to the latest version.
Closing this issue for now. If you still have issue please feel free to open a new issue.
