### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by StSaens** [JaccoR/hass-entso-e#129]
Is this still maintained?

**Comment by evading** [comment]
There's not a lot happening. I have considered to maintain a fork but I'm not sure about the license.

**Comment by JaccoR** [comment]
I am not having a lot of time to maintain this right now. I am open to give people who want to maintain some rights!

**Comment by andreas-berg** [comment]
Nice to hear from JaccoR.
I also had some issues with this version and ended up rewriting for my own use. 
I forked off JaccoRs project (good basis, thank you) but I do not intend to PR back. 
Anyone wanting to use my version can find it at [hass-entsoe-dayahead](https://github.com/andreas-berg/hass-entsoe-dayahead)

**Comment by Roeland54** [comment]
v0.4.0 is released this version contains fixes that solve a lot of warnings and known issues. This issue is probably also solved.
Please update to the latest version.
Closing this issue for now. If you still have issue please feel free to open a new issue.
