### ISSUE TITLE
Wrong date after db restore

### ISSUE THREAD

**Issue by rjvbeek** [JaccoR/hass-entso-e#136]
I have migrated to a new server for my HA installation. However, after restoring my backup, the date for the ENTSO-E hourly prices is wrong; they stay at the date from the backup's image. I have tried deleting the add-on from HA addons and from HACS and then reinstalling, but the problem persists. System date (server and HA) are correct. Any tips how I could solve this?

**Comment by Roeland54** [comment]
v0.4.0 is released this version contains fixes that solve a lot of warnings and known issues. This issue is probably also solved.
Please update to the latest version.
Closing this issue for now. If you still have issue please feel free to open a new issue.
