### ISSUE TITLE
Feature request: lowest prices within a range

### ISSUE THREAD

**Issue by MrOzzOnline** [JaccoR/hass-entso-e#14]
A flexible hourly contract usually is interesting when you consume a lot of electricity, like charging a car. This is usually done over a span of several hours. It would be nice to have this integration calculate the cheapest prices within a specific frame. For example: the cheapest 5 hours between 7pm and 7am

**Comment by ronaldt80** [comment]
I would like to be able to do something similar. However, i think that by following the format of nordpool the requirements can be met. There are lots of examples on the ha forum using templating to manipulate the data from nordpool, for example 3 consecutive hours of cheap energy etc.

**Comment by JaccoR** [comment]
This feature is covered in issue #15. Let's continue the discussion there. I'll close this for now.
