### ISSUE TITLE
After upgrading to HA 2024.4.0 no prices where retreived

### ISSUE THREAD

**Issue by sstolk90** [JaccoR/hass-entso-e#150]
I did reset my password @ Entsoe and my API key to be sure.
It shows this after reloading it all.
It has the prices of yesterday and the 3rd of April but after reloading the 5th is not showing up:
![image](https://github.com/JaccoR/hass-entso-e/assets/65487781/794bd99e-776b-418b-b1bc-e28cf824f846)
I've installed the update around 22:00

**Comment by ronaldt80** [comment]
Same here on 2024.03 version so it's probably the API.

**Comment by EpicCoolDude** [comment]
Yes, I also think this is not an issue regarding the upgrade to 2024.4.0. Same issue over here.
Also see: https://github.com/JaccoR/hass-entso-e/issues/149
The Entsoe API has returned errors.

**Comment by JSamsom72** [comment]
Same issue here. 

Core 2024.4.0
Supervisor 2024.03.1
Operating System 12.1
Frontend 20240403.1

**Comment by richardstroobach** [comment]
Same here. Not working after the update to 2024.4.0, but that might be a coincidence like @ronaldt80 mentioned he has is with 2024.3.
When I logged in to Entso-e website, I had to change my password. 

Data for The Netherlands looks empty on some pages:
![image](https://github.com/JaccoR/hass-entso-e/assets/7609610/a7276991-96d7-442d-854a-893d6a742820)

**Comment by sembeek** [comment]
Same here, I've sent an email to transparency@entsoe.eu to ask if it is a known issue.

**Comment by harryboer** [comment]
Same here since 2024.4.0

**Comment by TheBrankman** [comment]
Still on HA 2024.3.0, but same problem....

**Comment by TheBrankman** [comment]
I have found this in the log:
![Entso](https://github.com/JaccoR/hass-entso-e/assets/81829287/320a9da2-c69a-47e6-a0e3-fa919a74580c)

**Comment by chrkeijzer** [comment]
I got the same, on HA 2024.3.0. Switched over to the NordPool integration for now.

**Comment by sembeek** [comment]
Reactie van ENTSO-e:

The data was published on Transparency Platform by our Data Provider.
Could you please validate and confirm if we can consider the ticket closed?

En het lijkt nu inderdaad weer online te zijn!
Even de integratie reloaden in home assistant en de data komt tevoorschijn.

**Comment by sstolk90** [comment]
Not yet here. Even after a restart or reload of the integration

**Comment by TheBrankman** [comment]
Here also still no change after reboot or reload....

**Comment by richardstroobach** [comment]
Data on the Entso-e site are working again:

![image](https://github.com/JaccoR/hass-entso-e/assets/7609610/30859263-7270-44b6-b5b9-df8bc6ae71eb)

Still not working on HA after a restart of the addon and even after a restart of HA.

**Comment by TheBrankman** [comment]
But an other log entry now:
![entso2](https://github.com/JaccoR/hass-entso-e/assets/81829287/e9ace7c0-0f9a-4edb-9b8d-3cde346a2e1f)

**Comment by TheBrankman** [comment]
> Bij mij werkt het weer. Een nieuwe set services aanmaken met een andere naam.

Wat bedoel je daarmee?

**Comment by Arjanmus** [comment]
2 hours ago I reloaded/restarted the integration and restarted HA without luck. Just now checked the graph again with no intervention inbetween, and the prices are there. (updated around 3pm CEST)
Unclear what went wrong, but at least I have a beautiful graph for tomorrow😃👌

**Comment by sstolk90** [comment]
Still this in the log: 2024-04-05 15:31:24.658 DEBUG (MainThread) [custom_components.entsoe.coordinator] Fetching ENTSO-e data
2024-04-05 15:31:24.658 DEBUG (MainThread) [custom_components.entsoe.coordinator] NL
2024-04-05 15:31:26.538 DEBUG (MainThread) [custom_components.entsoe.coordinator] Finished fetching ENTSO-e coordinator data in 1.880 seconds (success: True)
2024-04-05 15:31:26.542 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.energieprijzen_current_electricity_market_price (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
2024-04-05 15:31:26.546 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.energieprijzen_next_hour_electricity_market_price (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
2024-04-05 15:31:26.551 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.energieprijzen_lowest_energy_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
2024-04-05 15:31:26.555 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.energieprijzen_highest_energy_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
2024-04-05 15:31:26.570 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.energieprijzen_average_electricity_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
2024-04-05 15:31:26.583 WARNING (MainThread) [custom_components.entsoe.sensor] Unable to update entity due to data processing error: None and error: min() iterable argument is empty
2024-04-05 15:31:26.583 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.energieprijzen_current_percentage_of_highest_electricity_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
2024-04-05 15:31:26.596 WARNING (MainThread) [custom_components.entsoe.sensor] Unable to update entity due to data processing error: None and error: min() iterable argument is empty
2024-04-05 15:31:26.597 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.energieprijzen_time_of_highest_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('timestamp') it is using; expected None; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
2024-04-05 15:31:26.610 WARNING (MainThread) [custom_components.entsoe.sensor] Unable to update entity due to data processing error: None and error: min() iterable argument is empty
2024-04-05 15:31:26.610 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.energieprijzen_time_of_lowest_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('timestamp') it is using; expected None; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues

**Comment by sstolk90** [comment]
> > Bij mij werkt het weer. Een nieuwe set services aanmaken met een andere naam.
> 
> Wat bedoel je daarmee?

So I have created a test Enstoe (just the name with same API key and now I see the data. So there is a difference what HA applies between versions I think

**Comment by TheBrankman** [comment]
Hm...I deleted the old entrance and created a new one with exact the same name. I think I got values, but the graphs are still empty.... I have to investigate further.

**Comment by huub66** [comment]
> > > Bij mij werkt het weer. Een nieuwe set services aanmaken met een andere naam.
> > 
> > 
> > Wat bedoel je daarmee?
> 
> So I have created a test Enstoe (just the name with same API key) and now I see the data. So there is a difference what HA applies between versions I think

Same here, only problem is that I lost the statistics on the new sensors as the naming is different and my pricing template is not working anymore so I am seeing only market prices without an uplift. Anyone facing this as well?

**Comment by harryboer** [comment]
> Hm...I deleted the old entrance and created a new one with exact the same name. I think I got values, but the graphs are still empty.... I have to investigate further.

Try deleting old configuration and create a new one with a different name, with the same name it doens't seem to work. Only problem is that you'll have to go through all the dashboards that use it to update with new name.

**Comment by harryboer** [comment]
> > > > Bij mij werkt het weer. Een nieuwe set services aanmaken met een andere naam.
> > > 
> > > 
> > > Wat bedoel je daarmee?
> > 
> > 
> > So I have created a test Enstoe (just the name with same API key) and now I see the data. So there is a difference what HA applies between versions I think
> 
> Same here, only problem is that I lost the statistics on the new sensors as the naming is different and my pricing template is not working anymore so I am seeing only market prices without an uplift. Anyone facing this as well?

It seems to only work when using a new name, but yes then need to update all the dashboards to the new entity name and you'll loose all historic data. Did you tick the box to fill in tax and template at the start when creating the configuration? I found out that when trying to apply afterwards it doesn't work (maybe it does with the new set of data tomorrow).

**Comment by wimwillems7325** [comment]
I removed the entso-e integration. Reinstall with another name. The same name is not working. I changed one character and it works!!

**Comment by patatman** [comment]
After reading this issue, I've also deleted my integration.
But I've managed to keep my history by doing the following:
1) Save/remember entity name
2) Delete the existing integration
3) Restart home assistant (THIS IS THE IMPORTANT PART)
4) Reconfigure integration with Same name from step 1 (or your previous install)
5) Find your history intact! 

Quitte a work-around, but it's working for now.

**Comment by RogMoe** [comment]
> I removed the entso-e integration. Reinstall with another name. The same name is not working. I changed one character and it works!!

...and what happened to your history? Previous time all this happened and reinstalled integration, I lost all historic data...

**Comment by richardstroobach** [comment]
Do we know what is causing this failure? Maybe then we can tackle this problem. I would like to keep historic data.

**Comment by StreborStrebor** [comment]
> Still this in the log:
> 
> ```
> 2024-04-05 15:31:24.658 DEBUG (MainThread) [custom_components.entsoe.coordinator] Fetching ENTSO-e data
> 2024-04-05 15:31:24.658 DEBUG (MainThread) [custom_components.entsoe.coordinator] NL
> 2024-04-05 15:31:26.538 DEBUG (MainThread) [custom_components.entsoe.coordinator] Finished fetching ENTSO-e coordinator data in 1.880 seconds (success: True)
> 2024-04-05 15:31:26.542 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.energieprijzen_current_electricity_market_price (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
> 2024-04-05 15:31:26.546 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.energieprijzen_next_hour_electricity_market_price (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
> 2024-04-05 15:31:26.551 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.energieprijzen_lowest_energy_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
> 2024-04-05 15:31:26.555 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.energieprijzen_highest_energy_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
> 2024-04-05 15:31:26.570 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.energieprijzen_average_electricity_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
> 2024-04-05 15:31:26.583 WARNING (MainThread) [custom_components.entsoe.sensor] Unable to update entity due to data processing error: None and error: min() iterable argument is empty
> 2024-04-05 15:31:26.583 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.energieprijzen_current_percentage_of_highest_electricity_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
> 2024-04-05 15:31:26.596 WARNING (MainThread) [custom_components.entsoe.sensor] Unable to update entity due to data processing error: None and error: min() iterable argument is empty
> 2024-04-05 15:31:26.597 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.energieprijzen_time_of_highest_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('timestamp') it is using; expected None; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
> 2024-04-05 15:31:26.610 WARNING (MainThread) [custom_components.entsoe.sensor] Unable to update entity due to data processing error: None and error: min() iterable argument is empty
> 2024-04-05 15:31:26.610 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.energieprijzen_time_of_lowest_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('timestamp') it is using; expected None; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
> ```

I have the exact same logs. It seems the Entities have changed classes (for example from Measurement to Monetary or Measurement to Timestamp).

Maybe deleting / reinstalling the integration configures it all correctly. But that would kill historic data.
Better would be to for the integration to fix the already configured entities, that no longer work.

**Comment by abroeders** [comment]
I guess if recreating the plugin instance with another name is solving this problem that it is a bug in this plugin. I'll wait until this bug is fixed.

**Comment by RogMoe** [comment]
Second it happened to me. I switched to Nordpool. Sorry
-------- Oorspronkelijk bericht --------Van: Arno Broeders ***@***.***> Datum: 13-04-2024  12:04  (GMT+01:00) Aan: JaccoR/hass-entso-e ***@***.***> Cc: RogMoe ***@***.***>, Comment ***@***.***> Onderwerp: Re: [JaccoR/hass-entso-e] After upgrading to HA 2024.4.0 no prices
  where retreived (Issue #150) 
I guess if recreating the plugin instance with another name is solving this problem that it is a bug in this plugin. I'll wait until this bug is fixed.

**Comment by Antyrael** [comment]
If you're using another integration that uses this Entso data, you'll need to change the sensor to "sensor.average_electricity_price_today". This sensor contains the hourly prices for the today and (sometime during the afternoon) tomorrow.

**Comment by nlmaca** [comment]
I had the same issue even before i upgraded to the latest HA version. I have had this same issue before that i had to reinstall the integration. 

The last release of this github page dates back to 2022. So i don't think there will come a new fix. So for the third time i 

I don't know where the problem came from this time or last time. I didn't bother to find out. In the end i knew i had to reinstall the integration again.

My first approach:
- Check API key if still valid
- Check account settings at entso-E
- Restart home assistant
- Reload integration

if all of this doesn't solve the issue, there is only one option left: reinstall the integration and link/replace all old entities to the new one. 

Just be sure to check your dashboards where you have used the old entities and replace them with the new one. 
For example these all gave me warnings and i just replaced them in my dashboard. 

```
sensor.current_electricity_market_price_2						sensor.entsoe_3_current_electricity_market_price
sensor.next_hour_electricity_market_price						sensor.entsoe_3_next_hour_electricity_market_price
sensor.average_electricity_price_today_2						sensor.entsoe_3_average_electricity_price_today
sensor.current_percentage_of_highest_electricity_price_today	sensor.entsoe_3_current_percentage_of_highest_electricity_price_today
sensor.highest_energy_price_today_2								sensor.entsoe_3_highest_energy_price_today
sensor.lowest_energy_price_today_2								sensor.entsoe_3_lowest_energy_price_today
sensor.time_of_highest_price_today								sensor.entsoe_3_time_of_highest_price_today							
sensor.time_of_lowest_price_today								sensor.entsoe_3_time_of_lowest_price_today		
```

**Comment by Antyrael** [comment]
You don't have to reinstall the integration.
If you delete the current configuration and add a new entry, using the same API key and settings as before, everything will work again.
But you are right that there are now new sensors you need to replace the old ones with where applicable.

**Comment by nlmaca** [comment]
Renewing the configuration did not work for me the first time i had this issue, so i didn't bother on checking again if it would work this time, but you're right it could be something to check before reinstalling it again.

I didn't care about history data, so this was the easiest and quickest.

**Comment by martin3000** [comment]
You have to delete the ensoe entries from .storage/core.restore_state

**Comment by PvaI** [comment]
> You have to delete the ensoe entries from .storage/core.restore_state

How do you proceed after deleting them? 

I've deleted all entso entries and reloaded HA, but old data is retained,
I've changed the last seen value to None / a date in the past and reload HA, but no change.
I've deleted the specific entry with hourly values and kept the file open, reloaded the integration and it still gets the wrong values from somewhere, these values are not in the core.restore_state file, it's only updated with the old values once I close the file.

I've queried my database, but entso data isn't stored there. I'll try to add the data to recorder and try to delete it there.

**Comment by martin3000** [comment]
I stopped HA, deleted the stored values and started HA. But that fixed only the "today" values, "tomorrow" was still wrong. So I fixed sth. in the code. If you have access to the custom_components/entsoe files, I can give you my fix.

**Comment by PvaI** [comment]
I have access, looking at your hass-entso-e repo now, do you have the change documented? or in comments in the affceted file? So I can re-apply / understand the fix :)

**Comment by martin3000** [comment]
The main change is  func async_get_last_sensor_data in sensor.py. It always returns "None" now.
I also changed coordinator.py, but I'm not sure if you need that.
Maybe the mean, max or min values will stop work. I did not check that.

**Comment by PvaI** [comment]
I'll check it out, I'm moving from the provided min/avg/max values; today the avg provided by Entso-E is below the min value :/ 
I'm checking out TheFes's work to get the optimal hours - [https://github.com/TheFes/cheapest-energy-hours](https://github.com/TheFes/cheapest-energy-hours)

**Comment by martin3000** [comment]
> I'm checking out TheFes's work to get the optimal hours

This looks pretty complex. I did not know that there is sth. like custom templates!

**Comment by PvaI** [comment]
You can import it through hacs, if you enable experimental features in HACS (Integrations -> Hacs - > Configure), you then still need to move the cheapest_energy_hours.jinja file from the www/community/cheapest-energy-hours folder to the custom_templates folder (which you may need to create at the same level as the www & custom_components folders.

I then used the following in the template editor to get some results, later I'll create some sensors or automations with them. 
There's some more stuff you can do with weighted hours, still figuring this out myself ;)

`{%- set sensor = 'sensor.entso_average_electricity_price_today' -%}
{% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
Cheapest 3 hour period tonight: 
{{ cheapest_energy_hours(sensor=sensor, attr_today='prices_today', attr_tomorrow='prices_tomorrow', time_key='time', value_key='price', hours=all, start='21:00', end=today_at('09:00') + timedelta(days=1), look_ahead=true) }}
Cheapest 3 hour period tomorrow: 
{{ cheapest_energy_hours(sensor=sensor, attr_today='prices_today', attr_tomorrow='prices_tomorrow', time_key='time', value_key='price', hours=all, start='09:00', end=today_at('21:00') + timedelta(days=1), look_ahead=true) }}`

**Comment by JaySea77** [comment]
Happened to me again in the last couple days. Have to remove and add the integration with a new name again...

**Comment by richardstroobach** [comment]
And again, after updating to the latest Home Assistant release, I have no data. Tried reinstalling with another name, but no luck this time. Can't this be solved permanently?

**Comment by JaySea77** [comment]
> And again, after updating to the latest Home Assistant release, I have no data. Tried reinstalling with another name, but no luck this time. Can't this be solved permanently somehow? 

Haven't tried to do the trick again, and updated my ha today, so might be broken since today.

**Comment by wilfredktlr** [comment]
This happened again today (for the second time). You can either create a new integration with a different name (this sucks because you also have to change the name in the automations and you lose the history) or use [this fix](https://github.com/JaccoR/hass-entso-e/issues/155#issuecomment-2155882331) (which worked for me).

I'm not sure what the underlying cause is. Maybe [this issue](https://github.com/JaccoR/hass-entso-e/issues/156) has something to do with it.

**Comment by PvaI** [comment]
I didn't upgrade and I had implemented Martin's fix, still broke. Trying to clear config/.storage/core.restore_state entries now...

**Comment by StreborStrebor** [comment]
> I didn't upgrade and I had implemented Martin's fix, still broke. Trying to clear config/.storage/core.restore_state entries now...
> 
> Update: Clearing the entries from core.restore_state worked.

I only needed to clear this object (including all the nested today and tomorrow prices that seemed to be stuck since 6 days ago): **sensor.[your entso-e config name]_average_electricity_price_today**

Prices and graphs filled almost immediately after starting hass again.

**Comment by StreborStrebor** [comment]
> > I only needed to clear this object (including all the nested today and tomorrow prices that seemed to be stuck since 6 days ago): **sensor.[your entso-e config name]_average_electricity_price_today**
> > Prices and graphs filled almost immediately after starting hass again.
> 
> Can you say how to clear the object including the nested today and tomorrow prices?

Sure,

SSH into your HASS
Shut down HASS with `ha core stop`
Make a backup of the state config file `cp config/.storage/core.restore_state config/.storage/core.restore_state.bak`
Edit it: `nano config/.storage/core.restore_state`

Remove this segment starting with the `{`

```{
      "state": {"entity_id":"sensor.dynamischeenergieprijzen_average_electricity_price_today","state":"0.26295","attributes":{"state_class":"measurement","prices_today":[{"time":"2024-06-14 00:00:00+02:00","price":0.25825},{"time":">
      "extra_data": {
        "native_value": 0.26295,
        "native_unit_of_measurement": null,
        "_attr_extra_state_attributes": {
          "prices_today": [
            {
              "time": "2024-06-14 00:00:00+02:00",
              "price": 0.25825
            },
            {
              "time": "2024-06-14 01:00:00+02:00",
              "price": 0.24494
            },

...cut to keep this readably short...

            {
              "time": "2024-06-14 23:00:00+02:00",
              "price": 0.3043
            }
          ],
          "prices_tomorrow": [],
          "prices": [
            {
              "time": "2024-06-13 00:00:00+02:00",
              "price": 0.29839
            },

...cut to keep this readably short...

            {
              "time": "2024-06-14 22:00:00+02:00",
              "price": 0.30842
            },
            {
              "time": "2024-06-14 23:00:00+02:00",
              "price": 0.3043
            }
          ]
        }
      },
      "last_seen": "2024-06-14T07:15:22.322960+00:00"
    },
```
Restart HASS with `ha core start`

**Comment by TheLion** [comment]
> > I didn't upgrade and I had implemented Martin's fix, still broke. Trying to clear config/.storage/core.restore_state entries now...
> > Update: Clearing the entries from core.restore_state worked.
> 
> I only needed to clear this object (including all the nested today and tomorrow prices that seemed to be stuck since 6 days ago): **sensor.[your entso-e config name]_average_electricity_price_today**
> 
> Prices and graphs filled almost immediately after starting hass again.

Clearing this one object solved the issue for me. 

Hopefully there will be a fix soon, that fixes it permanently ;-)

**Comment by DannyOosterveer** [comment]
This is a quite persistent and annoying error. I've been using the integration for over two years. Everytime the ENTSO-e API had some error, and there is no data available for some time, the integration seems to corrupt the data in sensors. Even after the data in the API is correct again, you can't use the previous sensors anymore. You'll have to delete the integration, add it again and change all our automations etc. Probably some better error handling is necessary when receiving empty or wrong data from the API...

**Comment by JaySea77** [comment]
> Sure,
> 
> SSH into your HASS Shut down HASS with `ha core stop` Make a backup of the state config file `cp config/.storage/core.restore_state config/.storage/core.restore_state.bak` Edit it: `nano config/.storage/core.restore_state`
> 
> Remove this segment starting with the `{`

where should the config dir be? I managed to get the ha core to stop, but I cannot find the file you are refering to.

**Comment by Roeland54** [comment]
v0.4.0 is released this version contains fixes that solve a lot of warnings and known issues. This issue is probably also solved.
Please update to the latest version.
Closing this issue for now. If you still have issue please feel free to open a new issue.

**Comment by ronaldt80** [comment]
Dont think its resolved.. my **prices tomorrow** attribute is empty; **prices today** contains today's prices and **prices** attribute contains prices of yesterday and tomorrow.

**Comment by richardstroobach** [comment]
Here the same as @ronaldt80.

**Comment by Roeland54** [comment]
The entso-e platform does not respond with the prices of tomorrow a.t.m. So the issue you currently experiencing is not related to the integration.

**Comment by JaySea77** [comment]
It happened again today so the 0.4.0 update didn't fix the issue.

**Comment by Roeland54** [comment]
The entso-e platform did not return prices for today until it was almost noon. Currently the integrations does not handle this properly. We are working on this.: Follow-up on this in issue #171. But entso-e being 20 hours late with prices is something we can't solve.

V0.4.0 should have automatically recovered this afternoon without user intervention.  If this is not the case feel free to open a new issue with detailed information about your config.

**Comment by JaySea77** [comment]
I noticed the current today prices are the prices of 3 days ago. How can I force the data to update?
