### ISSUE TITLE
Different price for input vs output

### ISSUE THREAD

**Issue by thoutenbos** [JaccoR/hass-entso-e#151]
Some energy providers in the NL are now applying their own costs separately to delivered and again on returned energy. Currently this is already the case for Frank Energy, EasyEnergie and NextEnergy.

Delivery:
current_price + (current_price|abs) * s.VAT + (s.energie_belasting **+** s.NextEnergy) * (1+s.VAT) )

Return:
current_price + (current_price|abs) * s.VAT + (s.energie_belasting **-** s.NextEnergy) * (1+s.VAT) )

Is there a way to implement this new pricing model?
It would require two different attributes as we would not know beforehand if we will be using or delivering energy for a given hour.

**Comment by RobKuipers** [comment]
In reply to the last sentence above: FYI it's not exclusive. We often both use **and** provide during an hour.

**Comment by thoutenbos** [comment]
I thought the in+out is netted for every hour as part of "salderen" before the costs factor is applied. Is that not correct?

**Comment by RobKuipers** [comment]
I'm afraid not. Provider (in your case NextEnergy) costs are applied for all currents flowing in- and out of your house. 
'Salderen' is something different: (some) taxes are applied only to your nett yearly usage.

**Comment by thoutenbos** [comment]
Very specific help page for NE, but afaik this is true for all the dynamic suppliers in NL

> Voor ieder uur salderen we hierbij jouw verbruik met jouw opwek. Indien je meer hebt verbruikt dan opgewekt, betaal je voor de overblijvende volumes de corresponderende uurprijs. Indien je meer hebt opgewekt dan verbruikt, dan krijg je de uurprijs vergoed voor de overblijvende volumes. Je betaalt alleen belasting over jouw netto verbruik per jaar.

https://www.nextenergy.nl/veelgestelde-vragen/ik-heb-zonnepanelen-en-maak-gebruik-van-salderingsregels-kan-dat-ook-bij-nextenergy

**Comment by RobKuipers** [comment]
I stand corrected!

**Comment by Roeland54** [comment]
So I would advise to just setup some home assistant template helpers to create sensors for consumption and return. Just set the VAT to 0 and the template to the default so you have the unmodified energy price. I do not see any real benefit in building this into the integration. Maybe later when the integration is stable.
