### ISSUE TITLE
homeassistant.util.loop

### ISSUE THREAD

**Issue by Erwiiinst** [JaccoR/hass-entso-e#152]
Logger: homeassistant.util.loop
Bron: util/loop.py:99
Eerst voorgekomen: 20:24:51 (1 gebeurtenissen)
Laatst gelogd: 20:24:51

Detected blocking call to import_module inside the event loop by custom integration 'entsoe' at custom_components/entsoe/coordinator.py, line 97: yesterday = pd.Timestamp.now(tz=str(time_zone)).replace(hour=0, minute=0, second=0) - pd.Timedelta(days = 1) (offender: /usr/local/lib/python3.12/site-packages/pandas/compat/_optional.py, line 132: module = importlib.import_module(name)), please create a bug report at https://github.com/JaccoR/hass-entso-e/issues

**Comment by Roeland54** [comment]
v0.4.0 is released this version contains fixes that solve a lot of warnings and known issues. This issue is probably also solved.
Please update to the latest version.
Closing this issue for now. If you still have issue please feel free to open a new issue.
