### ISSUE TITLE
Warning message; to be solved before HA Core update 2025.1

### ISSUE THREAD

**Issue by Erwiiinst** [JaccoR/hass-entso-e#165]
Logboek Details (WAARSCHUWING)
Logger: homeassistant.const
Bron: helpers/deprecation.py:197
Eerst voorgekomen: 19:54:05 (1 gebeurtenissen)
Laatst gelogd: 19:54:05

ENERGY_KILO_WATT_HOUR was used from entsoe, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please report it to the author of the 'entsoe' custom integration

**Comment by Roeland54** [comment]
v0.4.0 is released this version contains fixes that solve a lot of warnings and known issues. This issue is probably also solved.
Please update to the latest version.
Closing this issue for now. If you still have issue please feel free to open a new issue.
