### ISSUE TITLE
Feature request: VAT

### ISSUE THREAD

**Issue by jpulakka** [JaccoR/hass-entso-e#17]
In many if not most countries, VAT is added on top of electricity price.

This should be an option in the config flow. The default could be country-dependent, but such list may also be hard to maintain because VATs keep changing, e.g. https://github.com/custom-components/nordpool/issues/163 and might also depend on business/private use or even on the part of the country, https://github.com/custom-components/nordpool/pull/170

Alternatively or additionally it could be calculated in the additional_cost template https://github.com/JaccoR/hass-entso-e/issues/10 by providing current electricity price to the template.

**Comment by JaccoR** [comment]
I'm looking into getting the current price into the template. Next to that I agree that updating the VAT of all countries can be tiring. Maybe a default value can be shown per country in the config flow while still being able to edit it. This way it is not a big deal if the VAT is outdated or not right.

**Comment by JaccoR** [comment]
Currently working on getting VAT in the integration. If you want to help check #38!

**Comment by JaccoR** [comment]
This has been implemented in the new release!
