### ISSUE TITLE
Prices for Finland shifted one hour

### ISSUE THREAD

**Issue by lindsand** [JaccoR/hass-entso-e#177]
Prices for Finland are shifted one hour ahead, for example the price for 07:00 is actually the one for 08:00
- version 0.5.0-beta1

Can it have something to do with the time zone and daylight saving time as it can be interpreted like this:
entso-e thinks it's 07:00 when it's actually 08:00 so lagging one hour behind, we wake up one hour earlier during the summer

https://en.wikipedia.org/wiki/Time_in_Finland#:~:text=Finland%20uses%20Eastern%20European%20Time,UTC%2B03%3A00).

Finland uses Eastern European Time (EET) during the winter as standard time and Eastern European Summer Time (EEST) during the summer as daylight saving time. EET is two hours ahead of coordinated universal time (UTC+02:00) and EEST is three hours ahead of coordinated universal time (UTC+03:00).

So time zone to use is EET/EEST

entso-e
- time: '2024-09-13 07:00:00+03:00'
price: 0.44819...................................................<==== this should be for 08:00-09:00
- time: '2024-09-13 08:00:00+03:00'
price: 0.43766
- time: '2024-09-13 09:00:00+03:00'
price: 0.31384
- time: '2024-09-13 10:00:00+03:00'
price: 0.40344
- time: '2024-09-13 11:00:00+03:00'
price: 0.36267
- time: '2024-09-13 12:00:00+03:00'
price: 0.31375

nordpool (checked from multiple sources):
- start: '2024-09-13T07:00:00+03:00'
end: '2024-09-13T08:00:00+03:00'
value: 0.314
- start: '2024-09-13T08:00:00+03:00'
end: '2024-09-13T09:00:00+03:00'
value: 0.448........................................................ <==== 
- start: '2024-09-13T09:00:00+03:00'
end: '2024-09-13T10:00:00+03:00'
value: 0.438
- start: '2024-09-13T10:00:00+03:00'
end: '2024-09-13T11:00:00+03:00'
value: 0.314
- start: '2024-09-13T11:00:00+03:00'
end: '2024-09-13T12:00:00+03:00'
value: 0.403
- start: '2024-09-13T12:00:00+03:00'
end: '2024-09-13T13:00:00+03:00'
value: 0.363

**Comment by Roeland54** [comment]
Thanks for testing and reporting. I have made a change to the mapping of the prices and released v0.5.0-beta3.
I tried to test it by changing the time zone of my test home assistant but it that didn't work. So I could not verify if this solves the issue. Could you test and report back?

**Comment by lindsand** [comment]
Yes, It's solved now, data matches with Nordpool and other sources.

Thank you for excellent reaction time, that was really fast!
