### ISSUE TITLE
Calling get_energy_prices action with empty integration name

### ISSUE THREAD

**Issue by rwegnerGermany** [JaccoR/hass-entso-e#178]
Hi,
I just updated to v0.5 and manually calling the get_energy_action via Developer Tools was not really succesful, because I couldn't select the Config Entry. My (I think with v0.4*) created integration was shown in the list, but could not be selected properly; it said something with empty name, I don't remember.
Solution was to "rename" my integration; name was empty. Now my modification template is considered in the shown response.

Ah, and the attributes "prices_today" and "prices_tomorrow" are new, aren't they?

**Comment by Roeland54** [comment]
Hi thanks for reporting. I can reproduce the issue when the integration name is empty.
This "get_energy_action" is a new feature. The attributes  "prices_today" and "prices_tomorrow" are not new.

**Comment by Roeland54** [comment]
Solved by adding a default configuration name when leaving the name field empty.
