### ISSUE TITLE
Entsoe api response parsing issue: PT15M data is not handled correctly

### ISSUE THREAD

**Issue by rwegnerGermany** [JaccoR/hass-entso-e#179]
Hi,
starting with v0.5, the forecast for tomorrow seems to be wrong and is not corrected/updated when the today comes closer.

![grafik](https://github.com/user-attachments/assets/7e57178c-14a9-4fa3-8a7e-24aa878a58d8)

Yesterday I saw, that prices for Sep. 22nd 00:00 onwards are most likely wrong (left magenta box) and was curious to see if they get corrected. No, today morning prices where wrong.

So I deleted the integration and re-added it. Prices for today are correct now (orange instead of green line) but for tomorrow they again do look not reasonable and I assume they will not get updated.

With v0.4.2 it worked perfectly!

(Germany. Prices checked with EVCC entso-e and my energy provider's website.)
Modification template:
{% set s = {"Arbeitspreis": 0.1984,"VAT": 1.19 } %}{{(current_price + s.Arbeitspreis/s.VAT) | float}}

**Comment by rwegnerGermany** [comment]
I just downgraded to v0.4.2 and I only see today's prices again:
![grafik](https://github.com/user-attachments/assets/e6e7d6ee-81e4-48fb-9328-6ed0c37d57fa)

In the afternoon prices for tomorrow will be available and downloaded and most likely be correct.

Maybe v0.5 downloads too far in the future and doesn't update already downloaded timestamps?

The "sawtooth" data for tomorrow in the post above looks a bit like PT15M forecast: big step up, about 4 small steps down, big step up,...
![grafik](https://github.com/user-attachments/assets/9e0c59b5-2679-4bd3-a279-8652aa68946b)

**Comment by Roeland54** [comment]
Hi thanks for reporting this issue. It seems like the data is not parsed correctly when there is also "PT15M" returned in the response.

**Comment by Roeland54** [comment]
Released v0.5.1 with a fix for this. Can you test this?

**Comment by rwegnerGermany** [comment]
Thanks, looks good so far!
