### ISSUE TITLE
Feature request: Add possibility to change pricing units

### ISSUE THREAD

**Issue by alaraun** [JaccoR/hass-entso-e#180]
It would be super nice to have a possibility to change price units.
I'm especially interested in €/MWh.

Thanks

**Comment by Roeland54** [comment]
If it gets contributed I wouldn't have anything against it. But the focus currently is more on the stability of the integration and not on adding features. 

I would advise anyone who needs manipulations like this to use a [template helper](https://www.home-assistant.io/integrations/template).

**Comment by Roeland54** [comment]
Thank you for your contribution. This will be released in the next weeks.
