### ISSUE TITLE
Time information in the Entsoe data

### ISSUE THREAD

**Issue by han-alink** [JaccoR/hass-entso-e#182]
The time in the entsoe data is shown as follows:

- time: '2024-09-27 01:00:00+02:00'
price: 0.15257

Is the price valid for 01:00 or 03:00?
Is the UTC difference taken inrto account in the calculations?

**Comment by Roeland54** [comment]
The price is valid for your local time of '2024-09-27 01:00:00'. The '+02:00' shows that the local time is 'UTC +2'
Calculations are using local time.
