### ISSUE TITLE
Upgrade to 0.5.1 faulty

### ISSUE THREAD

**Issue by fbijma2** [JaccoR/hass-entso-e#184]
Since I upgraded to 0.5.1 version I do not get updated data anymore.

Logger: custom_components.entsoe.sensor
Source: custom_components/entsoe/sensor.py:233
integration: ENTSO-e Transparency Platform ([documentation](https://github.com/JaccoR/hass-entso-e), [issues](https://github.com/JaccoR/hass-entso-e/issues))
First occurred: 14:51:49 (8 occurrences)
Last logged: 14:51:49

    Unable to update entity 'entsoe.Highest energy price': No valid data for today available.
    Unable to update entity 'entsoe.Average electricity price': No valid data for today available.
    Unable to update entity 'entsoe.Current percentage of highest electricity price': No valid data for today available.
    Unable to update entity 'entsoe.Time of highest price': No valid data for today available.
    Unable to update entity 'entsoe.Time of lowest price': No valid data for today available.

There should be valid data I think
The integration was again reinstalled and restarted HA. But no suc6 unfortunately.

**Comment by vkanev** [comment]
I am getting the same log messages BUT without doing anything to the integration. Today I saw that at some point there is no more data received from API. I think there is some problem in entso-e API.
`2024-10-04 15:52:59.501 DEBUG (MainThread) [custom_components.entsoe.coordinator] ENTSO-e DataUpdateCoordinator data update
2024-10-04 15:52:59.501 DEBUG (MainThread) [custom_components.entsoe.coordinator] BG
2024-10-04 15:52:59.501 DEBUG (MainThread) [custom_components.entsoe.coordinator] fetching prices for start date: 2024-10-03 00:00:00+03:00 to end date: 2024-10-05 23:00:00+03:00
2024-10-04 15:52:59.503 DEBUG (SyncWorker_32) [custom_components.entsoe.api_client] Performing request to https://web-api.tp.entsoe.eu/api with params {'documentType': 'A44', 'in_Domain': '10YCA-BULGARIA-R', 'out_Domain': '10YCA-BULGARIA-R', 'securityToken': 'secret', 'periodStart': '202410030000', 'periodEnd': '202410052300'}
2024-10-04 15:53:09.621 DEBUG (MainThread) [custom_components.entsoe.coordinator] received data = {}
2024-10-04 15:53:09.621 DEBUG (MainThread) [custom_components.entsoe.coordinator] received pricing data from entso-e for 0 hours
2024-10-04 15:53:09.621 DEBUG (MainThread) [custom_components.entsoe.coordinator] Finished fetching ENTSO-e coordinator data in 10.120 seconds (success: True)`

**Comment by rwegnerGermany** [comment]
Same here for germany Region. Since 13:00 local Time entities are unavailable. Also on entsoe.eu Website an error occurs for fermentiert; not just „on data“

**Comment by fbijma2** [comment]
Thanks for this info, because I started to early trying to fix the add-on, I missed this.
That's probably because I updated yesterday and thought wrong that the add-on was faulty.

**Comment by fbijma2** [comment]
Might it have to do with the following>:

Dear Transparency Platform users,

 

We would like to inform you that starting from 01.10.2024, data is planned to be migrated from Day-Ahead Prices [12.1.D] to Energy Prices [12.1.D]. The migration is expected to be completed by 03.10.2024. The Transparency Platform team will provide a confirmation message upon completion of the migration.

 

Important remarks for users:

 

    Transparency Platform Website: After the migration is complete, all data  (historical and new publications) will be available on [this](https://newtransparency.entsoe.eu/market/energyPrices) link.
    SFTP users: All 12.1.D data will be available in the extract "EnergyPrices_12.1.D_r3". (Synchronization is expected to take up to 1 day after the migration.). You can find detailed specifications in the [new SFTP user guide](https://transparency.entsoe.eu/content/static_content/Static%20content/knowledge%20base/SFTP%20guide.html). The extract "DayAheadPrices_12.1.D" will no longer be updated.
    All XML exports, including those accessed through the Web API, Subscription, or Manual XML download, are designed to optimize data representation through variable-sized blocks using the A03 curve type ([link to curveType documentation](https://eepublicdownloads.entsoe.eu/clean-documents/EDI/Library/cim_based/Introduction_of_different_Timeseries_possibilities__curvetypes__with_ENTSO-E_electronic_document_v1.4.pdf)).
    The XLSX and CSV export functionality from the website is not fully operational. The exported document may contain incomplete data. This issue will be resolved in a future version of the system.
    New Data Item is designed to handle numbers with a maximum of 12 positions in total, including the possibility of up to 6 decimal positions. Any data that exceeds the decimal limit will still be processed, but only truncated values will be stored.
    To ensure proper functionality, you may need to delete saved data (cookies and site data) associated with the https://newtransparency.entsoe.eu/ website.
    The following additional attributes will be added to the API response and XML downloads:
        auction.type
        contract_MarketAgreement.type
        classificationSequence_AttributeInstanceComponent.position
    API Response should be validated against [XSD iec62325-451-3-publication_v7_3.xsd](https://gitlab.entsoe.eu/transparency/xsd/-/blob/04aaba6ffd8701496633c24347247ea0e9963f1c/iec62325-451-3-publication_v7_3.xsd) 

 

In case you have any questions regarding the planned activities, please don't hesitate to contact us at transparency@entsoe.eu.

 

Kind regards,

Transparency Platform team

**Comment by Roeland54** [comment]
I have identified a problem with the parsing of the xml. I am working on a fix a.t.m. 
I will release a new version asap.

**Comment by fbijma2** [comment]
Thanks.
Such a dedication. Appreciate it!

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by be2881** [comment]
New version installed and issues are gone. Everyhing is working again. Thanks a lot. Superfast service.

**Comment by lindsand** [comment]
Yes, working again after downloading latest version.

Many thanks for fast and dedicated response!

**Comment by Roeland54** [comment]
I have changed a lot of the code in the interest of having a more stable integration in the future. The downside is that there are now new bugs introduced that we need to iron out. So stability should improve soon. (hopefully they also work on stability on the api side of entsoe)

**Comment by large** [comment]
Is it me, or all the prices for 05.10.2024 empty in Entso-E:
https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=GRAPH&areaType=BZN&atch=false&dateTime.dateTime=05.10.2024+00:00|CET|DAY&biddingZone.values=CTY|10Y1001A1001A65H!BZN|10YDK-2--------M&resolution.values=PT15M&resolution.values=PT30M&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

But all prices are visible https://newtransparency.entsoe.eu/ for 05.10.2024.
Did they change the API without notice?

**Comment by rwegnerGermany** [comment]
Yes, looks like the API has changed. Try to update to 0.6.1. Works perfectly for me!
@Roeland54 Thank you very much!

**Comment by large** [comment]
@rwegnerGermany 0.6.1 works fine for prices today, but not for tomorrow. Do you get tomorrow prices?

**Comment by rwegnerGermany** [comment]
Yes, I do. Up to tomorrow close to midnight as usual.
Have you tried calling the "Get energy prices" action manually?

**Comment by Roeland54** [comment]
Resolved by v0.6.1
