### ISSUE TITLE
Since v0.5 the sliding-mode stopped updating high/low prices each hour

### ISSUE THREAD

**Issue by Steven77nl** [JaccoR/hass-entso-e#186]
Since version v0.5.x when in sliding prices mode the integration stopped updating the highest and lowest prices each hour and shows high or low still in the past.

A few weeks ago I reverted back to version v0.4.2 to have this working again, but since today due to the updates on the Entso-e side and the quick release fix v06.1 (thank you btw) I can not revert to v0.4.2 anymore :) and stuck with the sliding prices not working again.

Doing a reload on the integration will make the prices update, with the correct sliding logic (so high/low prices only in the future) but it does not do it automatically at each hour interval anymore, only if I reload again.

**Comment by Roeland54** [comment]
If you would like to test you can install v0.6.2-beta1 from hacs.

**Comment by Steven77nl** [comment]
Thx @Roeland54
I installed 0.6.2 and next event where the high price should go down is in 3 hour from now.
I will let you know the result.

**Comment by Steven77nl** [comment]
Update:
Sliding prices are updating again in the 0.6.2 beta.
Thank you !

![image](https://github.com/user-attachments/assets/33dc57e1-b584-4d6c-be86-807984448416)
