### ISSUE TITLE
Cannot add multiple instances when selecting custom calculation.

### ISSUE THREAD

**Issue by JvHummel** [JaccoR/hass-entso-e#187]
Hi, I just noticed that it's not possible to add multiple instances of the integration when using the custom VAT template option. An error shows up; 'already_configured'.

When unselecting this option, I can create another instance just fine and then set up the template after that. It then continues to work.

Not sure if this is intended behaviour, but I figured it wouldn't hurt to at least communicate my observations.

While I'm here, I'd like to thank you for this project and the quick fixes that keep coming our way. Maybe you can consider adding a donation link.

**Comment by Roeland54** [comment]
If you would like to test you can install v0.6.2-beta1 from hacs.
