### ISSUE TITLE
Feature: Describe how you can show the prices in a graph

### ISSUE THREAD

**Issue by istaveren** [JaccoR/hass-entso-e#19]
Would be nice if you can show the prices per hour in a graph.

**Comment by JaccoR** [comment]
Using the [ApexCharts Card](https://github.com/RomRider/apexcharts-card) you can plot the prices by using the prices and hours in the attributes of the sensors like below.

Example graph:
<img src="https://user-images.githubusercontent.com/31140879/195382579-c87b3285-c599-4e30-867e-1acf9feffabe.png" width=50% height=50%>

Example lovelace code:
```
type: custom:apexcharts-card
graph_span: 24h
span:
  start: day
now:
  show: true
  label: Now
header:
  show: true
  title: Electriciteitsprijzen Vandaag (€/kwh)
series:
  - entity: sensor.current_electricity_market_price
    stroke_width: 2
    float_precision: 3
    type: column
    opacity: 1
    color: ''
    data_generator: |
      return entity.attributes.prices_today.map((record, index) => {
        return [record.time, record.price];
      });
```
