### ISSUE TITLE
Feature request: retaining entered integration info

### ISSUE THREAD

**Issue by ikke-zelf** [JaccoR/hass-entso-e#22]
After set up of the integration (without using the template for additional costs) I would like to make use of the additional costs template.
However when I go into the integration the API key and location is not retained. I have to reenter them.

Is it possible to retain this info in some way?

**Comment by JaccoR** [comment]
You're right. This is possible, as other integrations do this. I'll have to figure out how though.

**Comment by ikke-zelf** [comment]
You're doing a nice job! appreciate the effort from you!

**Comment by JaccoR** [comment]
The new commit does this now!
