### ISSUE TITLE
Feature request: Option for prices in c/kWh

### ISSUE THREAD

**Issue by Skippereezi** [JaccoR/hass-entso-e#24]
Cents/kWh in my opinion are easier to handle than prices in euros, so it would be nice to have an option in integration setup to use cents instead.

**Comment by JaccoR** [comment]
Why is it easier to handle exactly? If there are more people interested in this I can probably build this in.

**Comment by Skippereezi** [comment]
I mean for humans it's easier to talk and compare cents than euros and for displaying in dashboards etc. E.g. current cost is 8c/kWh vs. 0,08€/kWh. At least in Finland this is quite common way providers and people talk about it.

**Comment by SVH-Powel** [comment]
You can have a template like this: {{(current_price * 100.0) | float}}

**Comment by JaccoR** [comment]
thats a solution, however the unit will still be wrong. I might make an option to select your unit so it matches the currency of your template.

**Comment by Skippereezi** [comment]
I believe that solves only the current price, but not the prices in the attributes etc. When used in graphs for example, it should be same unit price that is used elsewhere.

**Comment by JaccoR** [comment]
The template should change all prices accordingly, so it should work in graphs as well.

**Comment by Skippereezi** [comment]
Oh yeah, thats true. I mixed it with templates inside Home Assistant.
