### ISSUE TITLE
No graph in apex chart with data_generator anymore

### ISSUE THREAD

**Issue by ikke-zelf** [JaccoR/hass-entso-e#25]
Strange, everything in order yesterday. Today I wanted to check out how the 48 hour view looked prior to the 15:00 hour information threshold for the next day.
Surprisingly the apex chart is empty... not even error, just empty chart.

If I remove the 'data_generator' part everything seems oke.
As updated for I believe the HA-core, this hassentso-e and I believe the apexcharts have been installed and I only know how to revert the core update, I have no idea where to start looking for the error.

anyone else experiencing this? and a pointer in the right direction?

![image](https://user-images.githubusercontent.com/65031378/196005460-bd429114-b9b6-4102-a6ba-d02884c9db29.png)

**Comment by blowk** [comment]
I had this also after updating the module.
My fix to add a new Apex graph and the other Apex graphs were working again.

Hopefully this would fix your issue.

**Comment by ikke-zelf** [comment]
no, no solution.
a new apex chart is working fine with the default configuration in it.
could it be that the ENTSO data is presented in a different format then previously?

strange thing is that I'm apparently the only one having this issue.
running this:

```
type: custom:apexcharts-card
graph_span: 48h
span:
  start: day
now:
  show: true
  label: Now
header:
  show: true
  title: Electriciteitsprijzen Entso (€/kwh)
series:
  - entity: sensor.current_electricity_market_price
    name: Prijs vandaag
    stroke_width: 2
    float_precision: 4
    type: column
    opacity: 2
    color: ''
    data_generator: |
      return entity.attributes.prices_today.map((record, index) => {
        return [record.time, record.price];
      });
    show:
      legend_value: false
  - entity: sensor.current_electricity_market_price
    name: Prijs morgen
    stroke_width: 2
    float_precision: 4
    type: column
    opacity: 2
    color: rgb(0,128,128)
    data_generator: |
      return entity.attributes.prices_tomorrow.map((record, index) => {
        return [record.time, record.price];
      });
    show:
      legend_value: false
yaxis:
  - decimals: 2
    apex_config:
      tickAmount: 6
```

**Comment by Mariusthvdb** [comment]
seeing only 24 hour predicted values in the attributes, it might just break the data_generator? Are there no errors in Inspector on that.

(having other hour price sensors we see the same, eg easyenergy: the next day values only being available after 16:00 hr on the day?)

**Comment by ikke-zelf** [comment]
Thanks for the test @Mariusthvdb . I was expecting the values for the next day only to appear around 3/4pm everyday, but strange thing is I don't see anything. While it was working before.
- already tried new api key but in the dev tools I can see all values being present under 'prices' / 'prices_today' / and (after 3pm the 'prices_tomorrow'
- tried reinstalling the apex charts, but a standard yaml example just works. hence the above presented yaml with the 'data_generator' also works

Am trying to pint point to the root cause, but can't seem to find it.
can you tell me which versions you are running? core/hacs etc

**Comment by ikke-zelf** [comment]
And @Mariusthvdb can you post your used yaml in the apex charts? as I see now you have different bar colors what was not in my yaml so I expect you to have used a different one (and am interested in the coloring myself

**Comment by Mariusthvdb** [comment]
haha, You found my discussion post already https://github.com/JaccoR/hass-entso-e/discussions/27

**Comment by ikke-zelf** [comment]
Clear to me now... Just to let you know, the Entso is available in HACS.

**Comment by ikke-zelf** [comment]
Found an interesting one related to my issue...
When using Google Chrome as my browser iso Safari (using an iMac) it all works out of the box. Returning to Safari gives the issue again.
Diving deeper to find the root cause of this but at least a big step in the right direction!

**Comment by Mariusthvdb** [comment]
> Clear to me now... Just to let you know, the Entso is available in HACS.

really, what's the search term, Ive tried it all, and no result...
also, there's no release, so  wonder what could be found by HACS?

**Comment by ikke-zelf** [comment]
Yes indeed that is it.
With the just released/committed version you are also able to keep the configuration settings (automatically)
