### ISSUE TITLE
Feature request: create Tomorrow sensors

### ISSUE THREAD

**Issue by Mariusthvdb** [JaccoR/hass-entso-e#28]
just like

<img width="427" alt="Schermafbeelding 2022-10-18 om 07 35 54" src="https://user-images.githubusercontent.com/33354141/196344575-a356a9f3-e7b4-4eaa-b148-d47bdfafc718.png">

**Comment by Mariusthvdb** [comment]
that should be handled in the integration indeed

currently we have an empty attribute `prices_tomorrow`: , which seems a bit odd too:

<img width="326" alt="Schermafbeelding 2022-10-18 om 07 32 11" src="https://user-images.githubusercontent.com/33354141/196405110-52a31d37-7923-41b4-98f5-9dcf3ba63a39.png">

**Comment by Mariusthvdb** [comment]
Guess it would be awesome to have those same sensors for both today and tomorrow.

Ultimately my goal would be to plan (and hopefully automate ) devices in the home.

Some indication of the cheapest moments in the next X hours would be the ultimate of usefulness...

**Comment by JaccoR** [comment]
So average, highest and lowest for tomorrow?

**Comment by Mariusthvdb** [comment]
yes please, and also the time of highest and lowest if possible

**Comment by Mariusthvdb** [comment]
uhm, no?
suppose I have my dishwasher filled and ready, or some other power consuming utility, and I want to activate those tomorrow at the cheapest hour, todays sensors are not very useful?
Not even talking about electricity heaters... turning off at peak prices of the next day, activated the evening before next days work day (away from home..)

**Comment by Damazinho** [comment]
Gas is also the one i'm really missing. I noticed that allmost all energy providers with flex prices in NL have always the same price for the whole day. My provider (EnergyZero) has an API (for today: https://mijn.easyenergy.com/nl/api/tariff/getlebatariffs?startTimestamp=2022-10-20T22%3A00%3A00.000Z&endTimestamp=2022-10-21T22%3A00%3A00.000Z&grouping=) but I don't have the knowledge to get the price of gas from the API into HA.

**Comment by Mariusthvdb** [comment]
here you go:

<img width="495" alt="Schermafbeelding 2022-10-21 om 16 17 54" src="https://user-images.githubusercontent.com/33354141/197217787-e26507c6-a52c-4ad3-acf4-eeb81a739d81.png">

je kan de kleuren aanpassen in bijgevoegde configuratie:

[rest sensor gasprijzen easyenergy_yaml.txt](https://github.com/JaccoR/hass-entso-e/files/9839882/rest.sensor.gasprijzen.easyenergy_yaml.txt)

kon geen yaml uploaden, dus maar in txt

**Comment by Damazinho** [comment]
> here you go:
> 
> <img alt="Schermafbeelding 2022-10-21 om 16 46 57" width="510" src="https://user-images.githubusercontent.com/33354141/197224308-2d59c653-8506-425a-9e84-d2a06a85ce25.png">
> 
> je kan de kleuren aanpassen in bijgevoegde configuratie:
> 
> [rest sensor gasprijzen easyenergy_yaml.txt](https://github.com/JaccoR/hass-entso-e/files/9840102/rest.sensor.gasprijzen.easyenergy_yaml.txt)
> 
> kon geen yaml uploaden, dus maar in txt

Wow, thanks! Is er ook nog een manier dat ik op een specifiek moment alleen de prijs ophaal? Aangezien de prijs om 6 uur 's morgens bekend wordt gemaakt en dan voor de rest van de dag geldt?

**Comment by Mariusthvdb** [comment]
Nee, ik ben daar zelf mee aan het puzzelen ook voor stroom, maar dat lukt nog niet.

Denk aan het hele verhaal in 1 attribute en dan per trigger template (op tijd) laten updaten.

Was mijn hoop....

Voor nu is dit het. Je kunt natuurlijk wel gewoon alles templates wat je maar wilt op basis van deze test sensor. Zie bv de 3 template sensors die ik er al aan had toegevoegd

**Comment by ikke-zelf** [comment]
[Q and A topic](https://github.com/JaccoR/hass-entso-e/discussions/33) toegevoegd waar ik een korte uitleg geef hoe de prijzen te koppelen. kan nog gedetailleerder maar het begin is er.

**Comment by Vinisz** [comment]
> here you go:
> 
> <img alt="Schermafbeelding 2022-10-21 om 16 46 57" width="510" src="https://user-images.githubusercontent.com/33354141/197224308-2d59c653-8506-425a-9e84-d2a06a85ce25.png">
> 
> je kan de kleuren aanpassen in bijgevoegde configuratie:
> 
> [rest sensor gasprijzen easyenergy_yaml.txt](https://github.com/JaccoR/hass-entso-e/files/9840102/rest.sensor.gasprijzen.easyenergy_yaml.txt)
> 
> kon geen yaml uploaden, dus maar in txt

Ziet er cool uit, maar ik ben nogal nieuw in HA, dus , hoe krijg ik dit erin ? copy/paste in een bepaalde config oid ?

**Comment by Mariusthvdb** [comment]
so here we are....
hope this can be re-opened, for the tomorrow sensors request. its now 22.45, and I have to decide to turn on the dishwasher now, or maybe do it tomorrow, at some point during the day, when the price might be better. Currently, the prices are still all for today:

<img width="494" alt="Scherm­afbeelding 2023-03-28 om 22 45 13" src="https://user-images.githubusercontent.com/33354141/228362888-b9784c66-58c4-4e3a-a724-57101328223c.png">

and dont pint to any moment in time tomorrow.
The attributes are there, so we could create manual template sensors. Which would be silly if the integration could provide them for us in a whim.

https://github.com/JaccoR/hass-entso-e/issues/28#issuecomment-1285066074 was commented before, but it simply does not hold, nor help to decide in these matters.

other example where we use the 'tomorrow' data:

<img width="507" alt="Scherm­afbeelding 2023-03-28 om 22 49 06" src="https://user-images.githubusercontent.com/33354141/228363565-af4f68eb-1580-4e36-bee1-4aa1f3f59a54.png">

on the left todays sun production, to the right, the forecast for tomorrow. Combine that with Entsoe tomorrow sensors, and would could have a system...

hope you would reconsider,
thanks
