### ISSUE TITLE
Feature request: Create release(s) and notes for informing user of changes made to the integration

### ISSUE THREAD

**Issue by sfstar** [JaccoR/hass-entso-e#43]
Currently the integration is maintained by releasing a new version (hacs commit id upgrade) when an new change is merged to the master branch.
The last change that was merged (for #36) contained a breaking change that required users to re-add the integration after upgrading.
It would be nice for end-users if the release notes were to inform them of the required action to get the integration working after upgrade.

So that end-users won't have to search / open issues in order to get everything working again.
Furthermore, this would also allow end users to better determine whether to upgrade at that time and what new features they could try out

**Comment by sfstar** [comment]
Completely understandable :) .
it's not the most fun thing to do (speaking from experience).

**Comment by JaccoR** [comment]
First release is a fact!
