### ISSUE TITLE
Question: update interval

### ISSUE THREAD

**Issue by sfstar** [JaccoR/hass-entso-e#51]
Currently the update interval for the integration is set to 15 minutes.
However, entsoe only publishes new data on 13:00 after which the next days hour prices are static.
Wouldn't it be better if the integration were to update less frequently (thereby creating less load on the entsoe API if usage of this integration takes of).
Or are there any (currently not seen by me) reasons why a more frequent update interval is desirable?

**Comment by JaccoR** [comment]
This is basically a remnant of when I used this integration differently in a very early state. The following code in sensor.py overrides this update interval to do this only every hour.

```
        # Schedule the next update at exactly the next whole hour sharp
        self._unsub_update = event.async_track_point_in_utc_time(
            self.hass,
            self._update_job,
            utcnow().replace(minute=0, second=0) + timedelta(hours=1),
        )
```

However, now this is indeed redundant and could be done once a day. Some restructuring of coordinator.py is necessary to do it once a day. Another problem is that not all prices of all countries are available at exactly 13:00.

**Comment by sfstar** [comment]
Once a hour is a great improvement over once every 15 minutes.
Did not know that not every country has their prices published at 13:00.
In that case once a hour seems only fair (you could possibly restrict the updates to hourly around the hours when new prices come available).

The code you qouted indicates that all integrations will update on the hour exactly.
Perhaps this might be shifted around a bit so that requests get spread over the first x minutes of the hour
