### ISSUE TITLE
Wrong calculation of VAT Belgium when using a template

### ISSUE THREAD

**Issue by MrOzzOnline** [JaccoR/hass-entso-e#54]
It seems to be the VAT is calculated after the price is modified by the template. In Belgium all additional costs are excluded from tax so it is:
price x VAT + costs; but the integration calculates it as (price + costs) x VAT.

This might be different in other countries and I can imagine a mix of costs is also possible for example (price + costs ) x VAT + tax_free_costs. So I guess a second option apart from {{current price}} is needed?

**Comment by JaccoR** [comment]
Oh, i did not know that. For now keep the VAT tariff to 0 and use the template to add VAT. 

If the way VAT is added is different in a lot of countries we might need to ditch the VAT feature at all. Then the template can handle this.

**Comment by ThorAlex87** [comment]
Same issue in Norway. Setting vat to 0 and using the template works fine.

Entso-e (and nordpool) gives the price without VAT for business and private users, but the grid companies include VAT since they communicate directly to the private end user and have different tariffs for business users.
