### ISSUE TITLE
Double names using two entities, add optional name to the display name?

### ISSUE THREAD

**Issue by MrOzzOnline** [JaccoR/hass-entso-e#55]
If you add a second entity using the optional name option the display name isn't modified, only the id name.
Suggestion add the name between brackets?

![image](https://user-images.githubusercontent.com/115424166/198850510-172258f9-c2e8-47db-9c5d-11801022bbb0.png)

**Comment by JaccoR** [comment]
Yes i can do that. So the format will be "Display name (name)".

**Comment by JaccoR** [comment]
It is now in the new commit. Try it out!
