### ISSUE TITLE
Unavailable entities

### ISSUE THREAD

**Issue by 87Vortex87** [JaccoR/hass-entso-e#60]
Hi all,

I'm currently experiencing issues with all entities in this Integration. Reloading or renewing integration doesn't seem to do anything. This problem is there since a couple days. Seems to be internal server error 500.

**Comment by sfstar** [comment]
Please try re-adding the integration. Most likely you recently updated after JaccoR and I changed some Id's around causing the integration to not work until it is deleted and re-added once.

**Comment by 87Vortex87** [comment]
> Please try re-adding the integration. Most likely you recently updated after JaccoR and I changed some Id's around causing the integration to not work until it is deleted and re-added once.
> 
> Edit: 
> After a second read:
> By renewing integration you refer to the act of deleting and setting up the integration again?

No, I added it again. That worked.
