### ISSUE TITLE
No attributes in current electricity market price

### ISSUE THREAD

**Issue by Teme-V** [JaccoR/hass-entso-e#65]
After most recent update Attributes are lost from Current electricity market price entity after most recent 0.1.2 update
attributes are still exist in Average electricity price today, so those are reachable still as well as using v0.1.1

**Comment by flippz** [comment]
Isnt that the change in 0.1.2?

**Comment by Teme-V** [comment]
Just read 0.1.2 notes and it's there in capitals... my bad
I'll close this one
