### ISSUE TITLE
Average electricity price today - should today/tomorrow attributes state change at midnight?

### ISSUE THREAD

**Issue by jyrkih** [JaccoR/hass-entso-e#77]
Just noticed that attributes `Prices today` and `Prices tomorrow` seem to update only when the next day prices are received. Would it make sense to update the attributes to reflect the date change? E.g. as of now, when tomorrow's prices are not yet known, `Prices today` attribute shows prices for yesterday, and `Prices tomorrow` show today's prices.

**Comment by JaccoR** [comment]
you are right. This came with the update of #71 of @sfstar . This could be fixed with an if else statement that checks if tomorrows prices are available, and then the returns the right slices.

**Comment by sfstar** [comment]
One small correction the behaviour for the datatoday and tommorow attributes was last changed in #62.

Specifically this code block determines:
```
        if parsed_data.size > 48:
            data_today = parsed_data[-48:-24].to_dict()
            data_tomorrow = parsed_data[-24:].to_dict()
        else:
            data_today = parsed_data[-24:].to_dict()
            data_tomorrow = {}

        return {
            "data": data_all,
            "dataToday": data_today,
            "dataTomorrow": data_tomorrow,
        }
```
And is referenced in:
```
            "prices_today": self.get_timestamped_prices(self.data["dataToday"]),
            "prices_tomorrow": self.get_timestamped_prices(self.data["dataTomorrow"]),
```
#71 didn't change this behaviour (at least as far as i'm able to see. However, if i'm incorrect and it was introduced by #71 i'm sorry)

**Comment by sfstar** [comment]
Upon further investigation one thing that might explain why #71 broke this behaviour is that only changing attributes is not enough to update the entity.
Since #71 did limit state changes for avg entity to on publish on default.
For now changing the behaviour of the entity to `rotation` should ensure the dataToday and dataTomorrow are correctly filled.
This will however also change your avg,min,max etc entity updates to only at midnight (instead of instantly when data is published).

**Comment by JaccoR** [comment]
Yes that is what I meant as well. The boolean can be true if the length of the list is greater than 24.

**Comment by Roeland54** [comment]
v0.5.0 is released. The discussed issues should be solved. Please feel free to open a new issue if you feel this is needed.
