### ISSUE TITLE
Charting issue (ApexCharts)

### ISSUE THREAD

**Issue by lazmo88** [JaccoR/hass-entso-e#78]
Hello, for some reason today ApexCharts example stopped working. As far as I can see data is updated and provided correctly, however the chart isn't reflecting the values.

Any thoughts?

![Screenshot_2022-11-19-13-01-12-53_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/25498972/202847544-d2f4761b-a8dc-4937-b3d5-76749296e232.jpg)
![Screenshot_2022-11-19-13-01-38-20_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/25498972/202847545-f4346247-4c56-4d00-8101-a8d4bb29472a.jpg)
![Screenshot_2022-11-19-13-03-14-93_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/25498972/202847546-b10fc7f2-4a36-406d-a7d8-8464d847aaa8.jpg)

**Comment by ikke-zelf** [comment]
what browser this is taken from?
Safari has issues with the apex-chart

**Comment by JaccoR** [comment]
Can't reproduce this. Is this still happening?

**Comment by jusii** [comment]
I just installed this this morning, an hour ago, and same problem. But I think the issue is that the data shows 2022-11-30 as today and 2022-12-01 as tomorrow. And that's why the chart looks like that.

state_class: measurement
prices_today: 
- time: '2022-11-30 01:00:00+02:00'
  price: 0.37219

...
prices_tomorrow: 
- time: '2022-12-01 01:00:00+02:00'
  price: 0.39056

**Comment by lazmo88** [comment]
Solution: https://community.home-assistant.io/t/custom-component-entso-e-day-ahead-energy-prices/467127/24?u=lazmo88

It is indeed issue with the today/tomorrow dates. Thanks to @RT1080 for pointing out solution 🙏

series:
  - entity: sensor.average_electricity_price_today_2
    show:
      legend_value: false
    stroke_width: 2
    float_precision: 3
    type: column
    opacity: 0.3
    color: '#1007f0'
    data_generator: |
      return entity.attributes.prices_today.map((record, index) => {
        return [record.time, record.price];
      });
  - entity: sensor.average_electricity_price_today_2
    show:
      legend_value: false
    stroke_width: 2
    float_precision: 3
    type: column
    opacity: 0.3
    color: '#07bef0'
    data_generator: |
      return entity.attributes.prices_tomorrow.map((record, index) => {
        return [record.time, record.price];
      });
