### ISSUE TITLE
Switch DK1 and DK2 labeling 

### ISSUE THREAD

**Issue by bottiger** [JaccoR/hass-entso-e#82]
Currently the two DK regions are labelled as this:

             "DK_1":{"code":"DK_1", "name":"Denmark Eastern (DK1)", "VAT":0.21, "Currency":"EUR"},
             "DK_2":{"code":"DK_2", "name":"Denmark Western (DK2)", "VAT":0.21, "Currency":"EUR"},

However, this is wrong. DK1 is west and DK2 is east.

https://www.google.com/search?q=dk1+dk2&client=firefox-b-d&sxsrf=ALiCzsaIaoY3syOTaDiNfjiF4nTpG80sBQ:1669292783473&source=lnms&tbm=isch&sa=X&ved=2ahUKEwi69Imb6Mb7AhViQfEDHWQGCAEQ_AUoAXoECAEQAw&biw=2560&bih=1315&dpr=1.5

**Comment by JaccoR** [comment]
you're right, i will update it right away!
