### ISSUE TITLE
Min / Max values with Extremas in ApexCharts

### ISSUE THREAD

**Issue by stijn-dhondt** [JaccoR/hass-entso-e#83]
Hi @JaccoR 

When using bellow option in the apex chart:
    show:
      extremas: true

these values are not being marked as minimum or maximum in the apex charts.
Am i missing something here?

Thx,
Stijn

**Comment by stijn-dhondt** [comment]
> Hi
> 
> I managed to get the min/max visible after playing around with the timestamp
> 
@lindsand,

makes wonders happen, it is still a workaround but got some usable stats now!

Thx!

**Comment by Roeland54** [comment]
v0.4.0 is released this version contains fixes that solve a lot of warnings and known issues. This issue is probably also solved.
Please update to the latest version.
Closing this issue for now. If you still have issue please feel free to open a new issue.
