### ISSUE TITLE
No data if internet is down

### ISSUE THREAD

**Issue by ThorAlex87** [JaccoR/hass-entso-e#84]
So my roomba tried to eat the power cable for the fiber converter tonight, and the second the connection went down the data from the integration dissapeared. This is a major issue considering this data may be used to control critical things like heating. Not sure why it would need an internet connection other than when fetching prices at 1400 anyways? The nordpool integration had no issues.

Log:

> Logger: custom_components.entsoe.coordinator
Source: helpers/update_coordinator.py:151
Integration: ENTSO-e Transparency Platform ([documentation](https://github.com/JaccoR/hass-entso-e), [issues](https://github.com/JaccoR/hass-entso-e/issues))
First occurred: 04:31:45 (2 occurrences)
Last logged: 04:31:46

    Error fetching ENTSO-e coordinator data: Unexcpected error when fetching ENTSO-e prices: HTTPSConnectionPool(host='web-api.tp.entsoe.eu', port=443): Max retries exceeded with url: /api?documentType=A44&in_Domain=10YNO-3--------J&out_Domain=10YNO-3--------J&securityToken=xxx&periodStart=202212012300&periodEnd=202212062200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x9dd66340>: Failed to establish a new connection: [Errno -3] Try again'))
    Error fetching ENTSO-e coordinator data: Unexcpected error when fetching ENTSO-e prices: HTTPSConnectionPool(host='web-api.tp.entsoe.eu', port=443): Max retries exceeded with url: /api?documentType=A44&in_Domain=10YNO-3--------J&out_Domain=10YNO-3--------J&securityToken=xxx&periodStart=202212012300&periodEnd=202212062200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x9a88d238>: Failed to establish a new connection: [Errno -3] Try `again'))`

 
Screenshot of the history of a few of the sensors from entso-e, and some of the sensors used to control my water heater and electric heat when I'm not home. 
[Entsoe network down](https://user-images.githubusercontent.com/111507745/205481094-75284855-566a-40e5-a45b-066688dd2977.jpg)

**Comment by sfstar** [comment]
The nature of this issue matches #86.

**Comment by JaccoR** [comment]
We'll continue this issue in #86
