### ISSUE TITLE
Feature request: Multiple currency support

### ISSUE THREAD

**Issue by overas** [JaccoR/hass-entso-e#9]
I only get "Current Day-Ahead Electricity Price" and "Next Hour Day-Ahead Electricity Price" in Euro. Is this correct? I use Norway Kr. Sand (NO2) in Area. I want to have the prices in NOK. 

![image](https://user-images.githubusercontent.com/37910044/193784857-8f13b11d-87b3-4ca9-be67-fc2e81632835.png)

Home Assistant 2022.9.7

**Comment by JaccoR** [comment]
Yes it's only in euro for now. Unfortunately the python library of ENTSO-e only gives prices in euro. I am not sure if the API of ENTSO-e can give prices in more currencies, otherwise we have to fetch exchange rates from another API (like OpenExchange) i think.

Before a solution in this integration is fixed, you can use the [open exchange rates integration](https://www.home-assistant.io/integrations/openexchangerates/) to convert euros to NOK.

**Comment by krsandvik** [comment]
I think this API supports NOK 
https://www.nordpoolgroup.com/en/trading/api/

**Comment by JaccoR** [comment]
The template can be used to convert euros:
Here is an example provided by @SVH-Powel.

```
{% set s = {
"day": 0.6676,
"night": 0.5426,
"cert": 0.01,
"vat": 1.25,
"eur": float(states('sensor.kurs_eur'), 10)
}
%}
{% if now().isoweekday() >= 1 and now().isoweekday() <= 5 %}
{% if now().hour >= 6 and now().hour < 22 %}
{{(current_price * s.eur * s.vat + s.day + s.cert) | float}}
{% else %}
{{(current_price * s.eur * s.vat + s.night + s.cert) | float}}
{% endif %}
{% else %}
{{(current_price * s.eur * s.vat + s.night + s.cert) | float}}
{% endif %}
```

Here `sensor.kurs_eur` can be changed to the sensor that gives you the exchange the rate for the currency you want.

**Comment by overas** [comment]
Thanks for the example. 
You can also make the sensor with the currect Euro to NOK: sensor.kurs_eur
I have taken the example from this norwegian forum: https://www.hjemmeautomasjon.no/forums/topic/11102-str%C3%B8mpriser/?do=findComment&comment=105596

```
  - platform: rest
    resource: https://data.norges-bank.no/api/data/EXR/B.EUR.NOK.SP?lastNObservations=1&format=sdmx-json
    name: kurs_eur
    scan_interval: 43200
    unit_of_measurement: NOK
    value_template: "{{ value_json['data']['dataSets'][0]['series']['0:0:0:0']['observations']['0'][0] }}"
```

Thank you for the help. I am closing the case.

**Comment by JaccoR** [comment]
I am currently working on a config flow where you could select a entity with a conversion rate and use that to convert to the currency you want. This field also needs to accept a float if people don't want to use a entity for it. 

If you want to help: see #38!
