### ISSUE TITLE
Wrong device_class timestamps

### ISSUE THREAD

**Issue by Dominic-070** [JaccoR/hass-entso-e#93]
the sensors sensor.time_of_lowest_price_today and sensor.time_of_highest_price_today have the device_class monetary, I think that should be timestamp.

![Screenshot_20221214_225144_Home Assistant](https://user-images.githubusercontent.com/62623885/207723746-b3ac936a-c579-4f55-a904-ee921c709083.jpg)

**Comment by Mariusthvdb** [comment]
correct. see also https://github.com/JaccoR/hass-entso-e/issues/64
