### ISSUE TITLE
incorrect lowest price time of day

### ISSUE THREAD

**Issue by Mariusthvdb** [JaccoR/hass-entso-e#96]
with the fixed PR in the timestamp for these sensors, this is revealed (today is dec 20th)

<img width="489" alt="Scherm­afbeelding 2022-12-20 om 10 37 27" src="https://user-images.githubusercontent.com/33354141/208634435-c9a44c28-86fa-400f-b592-ebe1e5ec3109.png">

while it should really be like

<img width="492" alt="Scherm­afbeelding 2022-12-20 om 10 37 33" src="https://user-images.githubusercontent.com/33354141/208634510-81745dc3-1ed0-4485-8dfc-21e5183a6ab6.png">

note the timestamp is indeed 1 day off:

<img width="567" alt="Scherm­afbeelding 2022-12-20 om 10 36 54" src="https://user-images.githubusercontent.com/33354141/208634610-cd790e3b-d5ec-4960-b65b-b5a9e60d976f.png">

instead of 

<img width="542" alt="Scherm­afbeelding 2022-12-20 om 10 37 16" src="https://user-images.githubusercontent.com/33354141/208634659-fe49e560-c224-47f6-b384-9c18a5bcfb61.png">

the correct timestamp is ,made by the custom intergration by @klaasnicolaas for the EnergyZero data

see:
<img width="500" alt="Scherm­afbeelding 2022-12-20 om 10 40 26" src="https://user-images.githubusercontent.com/33354141/208634901-9fb2d5e7-1c39-4d4c-bea1-7ad6031b2fc3.png">

**Comment by sfstar** [comment]
In what mode of calculation are you running with the integration?
And to double check: the timestamp format is now ok?

**Comment by Mariusthvdb** [comment]
dont think I understand what you are asking about the mode of calculation. 

(timestamp seems to be ok, that is, it is showing in the frontend correctly. only a day off ;-)

see this:

<img width="493" alt="Scherm­afbeelding 2022-12-21 om 10 57 35" src="https://user-images.githubusercontent.com/33354141/208877148-8963963b-a546-409b-8f5a-9d190085cf0e.png">

it just doesnt check todays prices and seems to go back a full day.

which is remarkable, because when I select 48 hours, these are not ready yet, and only todays prices are available:

<img width="500" alt="Scherm­afbeelding 2022-12-21 om 10 57 51" src="https://user-images.githubusercontent.com/33354141/208877383-6ce0b9ed-85ea-4f47-9bd9-fe328d9dc098.png">

**Comment by sfstar** [comment]
@Mariusthvdb you can find the selected calculation method in the `options` menu that you can access via the `configure` button on the entsoe integration.
Should look like this:
<img width="472" alt="Screenshot 2022-12-23 at 18 46 21" src="https://user-images.githubusercontent.com/6717280/209382089-2b139a25-28f0-484b-93ad-71c8694e7361.png">

Based on your selected method this could be related to #77 and #98

**Comment by JaccoR** [comment]
I am in publish and i am having the same problem. Would choosing another calculation method fix this?

**Comment by klaasnicolaas** [comment]
The hourprices list you get in your [_filter_calculated_hourprices](https://github.com/JaccoR/hass-entso-e/blob/main/custom_components/entsoe/coordinator.py#L181) function, does it consist of data from multiple days?

**Comment by JaccoR** [comment]
Highest price is also incorrect and therefore the percentage is also incorrect.

**Comment by lfdmn** [comment]
> The hourprices list you get in the [_filter_calculated_hourprices](https://github.com/JaccoR/hass-entso-e/blob/main/custom_components/entsoe/coordinator.py#L181) function, does it consist of data from multiple days?

If I understand the code correctly, if ```self.calculation_mode == CALCULATION_MODE["publish"]``` it'll return data for 72h or 48h which makes these guys incorrect if you expect the values to be for the current day?
```python
            "min_price": self.get_min_price(filtered_hourprices),
            "max_price": self.get_max_price(filtered_hourprices),
            "avg_price": self.get_avg_price(filtered_hourprices),
            "time_min": self.get_min_time(filtered_hourprices),
            "time_max": self.get_max_time(filtered_hourprices),
```

Or is this on purpose?

**Comment by martin3000** [comment]
I'm in publish mode and the "sensor.entsoe_highest_energy_price_today" is showing a price for tomorrow. 
Also, sensor.entsoe_time_of_highest_price_today is for tomorrow.

**Comment by Roeland54** [comment]
So it would be nice to hear some opinions on the calculation methods. 
Currently "rotation" is the only calculation method that uses only the data of "today". 
"sliding" is using data of today and tomorrow (if available) to calculate min/max,... . (so can change in the middle of the day when new prices arrive)
"publish" is using all available data which is yesterday, today and tomorrow (if available) to calculate min/max,...(so can change in the middle of the day when new prices arrive)

The naming of the entities suggest "sensor.entsoe_time_of_highest_price_today" that only data of today is being used. Publish is however the default option. 

I my opinion rotation is the most logical calculation method so we could change the default to rotation.
And I think we also should drop the "today" naming for the entities because it is confusing and only true for rotation.
And should we have 3 different calculation methods? Is publish useful for anyone? Maybe we could drop it?
All feedback appreciated.

**Comment by Roeland54** [comment]
The beta version of [v0.5.0-beta1](https://github.com/JaccoR/hass-entso-e/releases/tag/v0.5.0-beta1) does contain a lot of changes to improve reliability. I have checked the calculations of the min/max,... for the different settings and they should all work as documented.
Can you test and provide feedback?

**Comment by Roeland54** [comment]
v0.5.0 is released. The discussed issues should be solved. Please feel free to open a new issue if you feel this is needed.
